/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WifiRouteImport } from './routes/wifi'
import { Route as UrlInspectRouteImport } from './routes/url-inspect'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as SocialEngineeringRouteImport } from './routes/social-engineering'
import { Route as SmishingRouteImport } from './routes/smishing'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PhishingRouteImport } from './routes/phishing'
import { Route as PasswordsRouteImport } from './routes/passwords'
import { Route as MetadataRouteImport } from './routes/metadata'
import { Route as BreachRouteImport } from './routes/breach'
import { Route as IndexRouteImport } from './routes/index'

const WifiRoute = WifiRouteImport.update({
  id: '/wifi',
  path: '/wifi',
  getParentRoute: () => rootRouteImport,
} as any)
const UrlInspectRoute = UrlInspectRouteImport.update({
  id: '/url-inspect',
  path: '/url-inspect',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialEngineeringRoute = SocialEngineeringRouteImport.update({
  id: '/social-engineering',
  path: '/social-engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const SmishingRoute = SmishingRouteImport.update({
  id: '/smishing',
  path: '/smishing',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PhishingRoute = PhishingRouteImport.update({
  id: '/phishing',
  path: '/phishing',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordsRoute = PasswordsRouteImport.update({
  id: '/passwords',
  path: '/passwords',
  getParentRoute: () => rootRouteImport,
} as any)
const MetadataRoute = MetadataRouteImport.update({
  id: '/metadata',
  path: '/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const BreachRoute = BreachRouteImport.update({
  id: '/breach',
  path: '/breach',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/breach': typeof BreachRoute
  '/metadata': typeof MetadataRoute
  '/passwords': typeof PasswordsRoute
  '/phishing': typeof PhishingRoute
  '/quiz': typeof QuizRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smishing': typeof SmishingRoute
  '/social-engineering': typeof SocialEngineeringRoute
  '/two-factor': typeof TwoFactorRoute
  '/url-inspect': typeof UrlInspectRoute
  '/wifi': typeof WifiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/breach': typeof BreachRoute
  '/metadata': typeof MetadataRoute
  '/passwords': typeof PasswordsRoute
  '/phishing': typeof PhishingRoute
  '/quiz': typeof QuizRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smishing': typeof SmishingRoute
  '/social-engineering': typeof SocialEngineeringRoute
  '/two-factor': typeof TwoFactorRoute
  '/url-inspect': typeof UrlInspectRoute
  '/wifi': typeof WifiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/breach': typeof BreachRoute
  '/metadata': typeof MetadataRoute
  '/passwords': typeof PasswordsRoute
  '/phishing': typeof PhishingRoute
  '/quiz': typeof QuizRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smishing': typeof SmishingRoute
  '/social-engineering': typeof SocialEngineeringRoute
  '/two-factor': typeof TwoFactorRoute
  '/url-inspect': typeof UrlInspectRoute
  '/wifi': typeof WifiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/breach'
    | '/metadata'
    | '/passwords'
    | '/phishing'
    | '/quiz'
    | '/sitemap.xml'
    | '/smishing'
    | '/social-engineering'
    | '/two-factor'
    | '/url-inspect'
    | '/wifi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/breach'
    | '/metadata'
    | '/passwords'
    | '/phishing'
    | '/quiz'
    | '/sitemap.xml'
    | '/smishing'
    | '/social-engineering'
    | '/two-factor'
    | '/url-inspect'
    | '/wifi'
  id:
    | '__root__'
    | '/'
    | '/breach'
    | '/metadata'
    | '/passwords'
    | '/phishing'
    | '/quiz'
    | '/sitemap.xml'
    | '/smishing'
    | '/social-engineering'
    | '/two-factor'
    | '/url-inspect'
    | '/wifi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BreachRoute: typeof BreachRoute
  MetadataRoute: typeof MetadataRoute
  PasswordsRoute: typeof PasswordsRoute
  PhishingRoute: typeof PhishingRoute
  QuizRoute: typeof QuizRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SmishingRoute: typeof SmishingRoute
  SocialEngineeringRoute: typeof SocialEngineeringRoute
  TwoFactorRoute: typeof TwoFactorRoute
  UrlInspectRoute: typeof UrlInspectRoute
  WifiRoute: typeof WifiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wifi': {
      id: '/wifi'
      path: '/wifi'
      fullPath: '/wifi'
      preLoaderRoute: typeof WifiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/url-inspect': {
      id: '/url-inspect'
      path: '/url-inspect'
      fullPath: '/url-inspect'
      preLoaderRoute: typeof UrlInspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-engineering': {
      id: '/social-engineering'
      path: '/social-engineering'
      fullPath: '/social-engineering'
      preLoaderRoute: typeof SocialEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smishing': {
      id: '/smishing'
      path: '/smishing'
      fullPath: '/smishing'
      preLoaderRoute: typeof SmishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phishing': {
      id: '/phishing'
      path: '/phishing'
      fullPath: '/phishing'
      preLoaderRoute: typeof PhishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passwords': {
      id: '/passwords'
      path: '/passwords'
      fullPath: '/passwords'
      preLoaderRoute: typeof PasswordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metadata': {
      id: '/metadata'
      path: '/metadata'
      fullPath: '/metadata'
      preLoaderRoute: typeof MetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breach': {
      id: '/breach'
      path: '/breach'
      fullPath: '/breach'
      preLoaderRoute: typeof BreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BreachRoute: BreachRoute,
  MetadataRoute: MetadataRoute,
  PasswordsRoute: PasswordsRoute,
  PhishingRoute: PhishingRoute,
  QuizRoute: QuizRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SmishingRoute: SmishingRoute,
  SocialEngineeringRoute: SocialEngineeringRoute,
  TwoFactorRoute: TwoFactorRoute,
  UrlInspectRoute: UrlInspectRoute,
  WifiRoute: WifiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
